# Generated by Django 4.0 on 2022-12-02 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_bicyclemodels_user_id_infoperson_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bicyclemodels',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='infoperson',
            name='user_id',
        ),
    ]
