# Generated by Django 4.0 on 2022-12-05 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0010_alter_user_bicycle_alter_user_info_person_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_route', models.CharField(max_length=150, unique=True)),
                ('distance', models.CharField(blank=True, max_length=150, null=True)),
                ('time', models.DateTimeField(blank=True, null=True)),
                ('dificulty', models.CharField(choices=[('Easy', 'Easy'), ('Normaly', 'Normaly'), ('Deficult', 'Deficult')], default='Normaly', max_length=8)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
            ],
            options={
                'verbose_name': 'Route',
                'verbose_name_plural': 'Routes',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='UserRouterModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='router.routemodels')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
            options={
                'verbose_name': 'UserRouter',
                'verbose_name_plural': 'UserRoutes',
                'ordering': ['id'],
            },
        ),
    ]
