# Generated by Django 4.0 on 2022-12-06 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_user_bicycle_alter_user_info_person_and_more'),
        ('router', '0002_routemodels_user_id_delete_userroutermodels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routemodels',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user'),
        ),
    ]
