# Generated by Django 4.0 on 2022-12-07 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_user_bicycle_alter_user_info_person_and_more'),
        ('router', '0003_alter_routemodels_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRouterModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='router.routemodels')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
            options={
                'verbose_name': 'UserRouter',
                'verbose_name_plural': 'UserRoutes',
                'ordering': ['id'],
            },
        ),
    ]
