# Generated by Django 4.0 on 2022-12-07 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('router', '0004_userroutermodels'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routemodels',
            name='user_id',
        ),
    ]
