# Generated by Django 4.0 on 2022-11-16 19:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BikeGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('picture', models.ImageField(blank=True, default='default.jpg', upload_to='group/', verbose_name='foto group')),
                ('city', models.CharField(max_length=255)),
                ('user_id', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(default='default.jpg', upload_to='event/', verbose_name='event image')),
                ('route', models.CharField(max_length=255)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('bike_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group.bikegroups')),
            ],
        ),
        migrations.CreateModel(
            name='Bicycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=255)),
                ('picture', models.ImageField(default='default.jpg', upload_to='bicycle/', verbose_name='bicycle pic')),
                ('serial', models.CharField(max_length=255)),
                ('color', models.CharField(choices=[('WT', 'Blanco'), ('BK', 'Negro'), ('RD', 'Rojo'), ('GN', 'Verde'), ('YW', 'Amarillo'), ('BL', 'AZUL'), ('GR', 'Blanco'), ('PK', 'Blanco')], default='WT', max_length=2)),
                ('size', models.CharField(choices=[('SM', 'Small'), ('MD', 'Medium'), ('LG', 'Small'), ('XL', 'XLarge')], default='MD', max_length=2)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
        ),
    ]
