# Generated by Django 4.0 on 2022-11-16 21:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='route',
            new_name='end_route',
        ),
        migrations.RemoveField(
            model_name='event',
            name='bike_group',
        ),
        migrations.AddField(
            model_name='bikegroups',
            name='eventos',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='group.event'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='start_route',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='user_id',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bicycle',
            name='picture',
            field=models.ImageField(blank=True, default='profile.png', null=True, upload_to='bicycle/', verbose_name='bicyclepic'),
        ),
        migrations.AlterField(
            model_name='bikegroups',
            name='picture',
            field=models.ImageField(blank=True, default='group.png', upload_to='group/', verbose_name='foto group'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, default='event.png', null=True, upload_to='event/', verbose_name='event image'),
        ),
    ]
