# Generated by Django 4.0 on 2022-11-16 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_rename_route_event_end_route_remove_event_bike_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bikegroups',
            name='eventos',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='group.event'),
        ),
    ]
