# Generated by Django 4.0 on 2022-12-04 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0003_alter_groupusersrolmodel_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bikegroupsmodel',
            old_name='user_id',
            new_name='user_menber_id',
        ),
        migrations.RenameField(
            model_name='groupusersrolmodel',
            old_name='user_menber_id',
            new_name='user_id',
        ),
    ]
