# Generated by Django 4.0 on 2022-12-06 17:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('group', '0006_rename_user_menber_id_bikegroupsmodel_user_member_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bikegroupsmodel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bikegroupsmodel',
            name='user_member_id',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
