# Generated by Django 4.0 on 2022-12-06 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0007_alter_bikegroupsmodel_description_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GroupUsersRolModel',
        ),
        migrations.DeleteModel(
            name='RolesModel',
        ),
    ]
