# Generated by Django 4.0 on 2022-12-07 01:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('group', '0009_groupusersrolmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bikegroupsmodel',
            name='user_member_id',
            field=models.ManyToManyField(db_table='GroupUsersRolModel', to=settings.AUTH_USER_MODEL),
        ),
    ]
