# Generated by Django 4.0 on 2022-12-02 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('group', '0002_rolesmodel_groupusersrolmodel'),
        ('accounts', '0012_user_bicycle_user_info_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star_lat', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True)),
                ('star_lon', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True)),
                ('end_lat', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True)),
                ('end_lon', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('distance', models.DecimalField(decimal_places=1, max_digits=5)),
                ('difficulty', models.CharField(choices=[('Lento', 'Lento'), ('Moderado', 'Moderado'), ('Pro', 'Pro')], default='Moderado', max_length=8)),
                ('travel_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='UserRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='group.eventmodel')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
        ),
    ]
