# Generated by Django 4.0 on 2022-12-02 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_user_bicycle_alter_user_info_person_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bicycle',
        ),
        migrations.RemoveField(
            model_name='user',
            name='info_person',
        ),
    ]
