# Generated by Django 4.0 on 2022-12-02 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_remove_bicyclemodels_user_id_and_more'),
        ('accounts', '0011_remove_user_bicycle_remove_user_info_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bicycle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='info.bicyclemodels'),
        ),
        migrations.AddField(
            model_name='user',
            name='info_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='info.infoperson'),
        ),
    ]
